---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-default-tls
  namespace: networking
spec:
  secretName: external-default-tls
  issuerRef:
    name: letsencrypt-production-external
    kind: ClusterIssuer
  dnsNames:
  - "${EXTERNAL_DOMAIN}"
  - "*.${EXTERNAL_DOMAIN}"