apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: self-hosted
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-password
    creationPolicy: 'Orphan'
  data:
  - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
    remoteRef:
      key: kube/external-dns
      property: pihole-password