apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.home.${INTERNAL_DOMAIN}:8200"
      path: "kube"
      version: "v2"
      namespace: external-secrets
      auth:
        tokenSecretRef:
          namespace: external-secrets
          name: "vault-token"
          key: "token"