---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: ansible
spec:
  service_type: ClusterIP
  ingress_type: ingress
  ingress_annotations: |
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: networking-ipwhitelist@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-production-internal
  ingress_hosts:
    - hostname: ansible.home.${INTERNAL_DOMAIN}
      tls_secret: awx-tls
  # ingress_tls_secret: awx-tls
  ingress_class_name: traefik-internal
  hostname: ansible.home.${INTERNAL_DOMAIN}
  garbage_collect_secrets: true
  no_log: false
  
  web_resource_requirements:
    requests:
      cpu: 100m
      memory: .5G
    limits:
      memory: 2G
  task_resource_requirements:
    requests:
      cpu: 125m
      memory: .5G
    limits:
      memory: 2G
  ee_resource_requirements:
    requests:
      cpu: 125m
      memory: .5G
    limits:
      memory: 2G
  postgres_configuration_secret: postgres-secret
  # postgres_data_volume_init: true

# ref: https://github.com/ansible/awx-operator/blob/devel/roles/installer/defaults/main.yml