---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: ansible
spec:
  service_type: ClusterIP
  ingress_type: ingress
  ingress_tls_secret: awx-tls
  ingress_class_name: traefik-internal
  hostname: ansible.home.${INTERNAL_DOMAIN}
  garbage_collect_secrets: true
  no_log: false
  
  web_resource_requirements:
    requests:
      cpu: 100m
      memory: .5G
    limits:
      cpu: 500m 
      memory: 2G
  task_resource_requirements:
    requests:
      cpu: 125m
      memory: .5G
    limits:
      cpu: 500m
      memory: 2G
  ee_resource_requirements:
    requests:
      cpu: 125m
      memory: .5G
    limits:
      cpu: 500m
      memory: 2G