apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: ansible
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: database
    remoteRef:
      key: kube/awx-secret
      property: database
  - secretKey: host
    remoteRef:
      key: kube/awx-secret
      property: host
  - secretKey: password
    remoteRef:
      key: kube/awx-secret
      property: password
  - secretKey: port
    remoteRef:
      key: kube/awx-secret
      property: port
  - secretKey: sslmode
    remoteRef:
      key: kube/awx-secret
      property: sslmode
  - secretKey: target_session_attrs
    remoteRef:
      key: kube/awx-secret
      property: target_session_attrs
  - secretKey: type
    remoteRef:
      key: kube/awx-secret
      property: type
  - secretKey: username
    remoteRef:
      key: kube/awx-secret
      property: username