---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app harbor
  namespace: flux-system
spec:
  targetNamespace: harbor
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: traefik
    - name: longhorn
    - name: harbor-config
    - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/harbor/harbor/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app harbor-config
  namespace: flux-system
spec:
  targetNamespace: harbor
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
  path: ./kubernetes/apps/harbor/harbor/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets