---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-tls
  namespace: nextcloud
spec:
  secretName: nextcloud-tls
  issuerRef:
    name: letsencrypt-production-external
    kind: ClusterIssuer
  commonName: "nextcloud.${EXTERNAL_DOMAIN}"
  dnsNames:
  - "nextcloud.${EXTERNAL_DOMAIN}"