apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: nextcloud
    creationPolicy: 'Orphan'
  data:
  - secretKey: postgresql_password
    remoteRef:
      key: kube/nextcloud
      property: postgresql_password
  - secretKey: admin_user
    remoteRef:
      key: kube/nextcloud
      property: admin_user
  - secretKey: admin_password
    remoteRef:
      key: kube/nextcloud
      property: admin_password