---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg
  namespace: databases
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: kube/cnpg
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: kube/cnpg
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: username
    remoteRef:
      key: kube/cnpg
      property: POSTGRES_SUPER_USER
  - secretKey: password
    remoteRef:
      key: kube/cnpg
      property: POSTGRES_SUPER_PASS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres
  namespace: databases
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-postgres
    creationPolicy: 'Orphan'
  data:
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: kube/cnpg
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: kube/cnpg
      property: AWS_SECRET_ACCESS_KEY
  - secretKey: username
    remoteRef:
      key: kube/cnpg
      property: POSTGRES_SUPER_USER
  - secretKey: password
    remoteRef:
      key: kube/cnpg
      property: POSTGRES_SUPER_PASS
---