---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.16.2
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    expose:
      type: ingress
      tls:
        enabled: true
        certSource: secret
        secret:
          secretName: registry-tls
      ingress:
        hosts:
          core: registry.home.${INTERNAL_DOMAIN}
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: letsencrypt-production-internal
          traefik.ingress.kubernetes.io/router.middlewares: |
            networking-ipwhitelist@kubernetescrd,
            networking-request-limit@kubernetescrd
    externalURL: https://registry.home.${INTERNAL_DOMAIN}
    database:
      type: external
      external:
        host: enterprise-postgres-rw.databases.svc.cluster.local
        port: "5432"
        username: harbor
        coreDatabase: registry
        existingSecret: harbor-postgres
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry
    existingSecretAdminPassword: harbor-admin-password