---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.15.*
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    expose:
      type: ingress
      tls:
        enabled: true
        secret:
          secretName: registry-tls
      ingress:
        hosts:
          core: registry.home.${INTERNAL_DOMAIN}
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    externalURL: https://registry.home.${INTERNAL_DOMAIN}
    persistence:
      enabled: true
      persistentVolumeClaim:
        registry:
          existingClaim: harbor-registry
        jobservice:
          jobLog:
            storageClass: longhorn
            size: 1Gi
        database:
          storageClass: longhorn
          size: 1Gi
        redis:
          storageClass: longhorn
          size: 1Gi
        trivy:
          storageClass: longhorn
          size: 5Gi
    existingSecretAdminPassword: harbor-admin-password