---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tasks
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    controllers:
      tasks:
        initContainers:
          init-db:
            image:
              repository: ghcr.io/kwehen/postgres-init
              tag: latest
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: tasks-postgres-init
        containers:
          app:
            envFrom:
              - secretRef:
                  name: tasks-secrets
            image:
              repository: jeffhardyski/go-todo-oauth
              tag: latest
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-cloudflare-only@kubernetescrd
          cert-manager.io/cluster-issuer: letsencrypt-production-external
        hosts:
          - host: tasks.${EXTERNAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts: ["tasks.${EXTERNAL_DOMAIN}"]
            secretName: tasks-tls