apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tasks-external-secret
  namespace: tasks
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tasks-secrets
    creationPolicy: 'Orphan'
  dataFrom:
    - find:
        path: kube/tasks-todo
        name:
          regexp: ".*"