---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls 
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  issuerRef:
    name: letsencrypt-production-internal
    kind: ClusterIssuer
  commonName: "longhorn.home.${INTERNAL_DOMAIN}"
  dnsNames:
  - "longhorn.home.${INTERNAL_DOMAIN}"