---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app metallb
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/networking/metallb/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 1m
  retryInterval: 1m
  timeout: 5m

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app metallb-config
  namespace: flux-system
spec:
  targetNamespace: networking
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: metallb
  path: ./kubernetes/apps/networking/metallb/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 1m
  retryInterval: 1m
  timeout: 5m