---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: awx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: awx-operator
      # reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: flux-system
      version: 3.2.0
  interval: 24h
  releaseName: awx
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace