kind: HelmRelease
metadata:
  name: awx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: awx-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: awx-operator
        namespace: flux-system
      version: 2.19.0
  interval: 24h
  releaseName: awx
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
    cleanupOnFail: true
    crds: Create