apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: calendarbot-secret
  namespace: in-house
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: calendarbot-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: DISCORD_TOKEN
    remoteRef:
      key: kube/calendarbot
      property: DISCORD_TOKEN
  - secretKey: DB_NAME
    remoteRef:
      key: kube/calendarbot
      property: DB_NAME
  - secretKey: DB_USER
    remoteRef:
      key: kube/calendarbot
      property: DB_USER
  - secretKey: DB_PASSWD
    remoteRef:
      key: kube/calendarbot
      property: DB_PASSWD
  - secretKey: HOST
    remoteRef:
      key: kube/calendarbot
      property: HOST
  - secretKey: OLLAMA_HOST
    remoteRef:
      key: kube/calendarbot
      property: OLLAMA_HOST