---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dynatrace
  namespace: flux-system
spec:
  interval: 24h
  url: oci://public.ecr.aws/dynatrace/dynatrace-operator
  ref:
    tag: 1.3.2
