---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tasks
  namespace: flux-system
spec:
  targetNamespace: tasks
  dependsOn:
    - name: tasks-config
  path: ./kubernetes/apps/tasks/tasks/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  # postBuild:
  #   substituteFrom:
  #     - kind: Secret
  #       name: cluster-secrets
  #     - kind: ConfigMap
  #       name: cluster-settings
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tasks-config
  namespace: flux-system
spec:
  targetNamespace: tasks
  # dependsOn:
  #   - name: tasks
  path: ./kubernetes/apps/tasks/tasks/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings