apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: traefik
  namespace: networking
spec:
  scrapeInterval: 1m
  scrapeTimeout: 10s
  honorTimestamps: true
  staticConfigs:
    - labels:
        job: traefik
      targets:
        - traefik.traefik.svc.cluster.local:9100