---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ytmp3
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      ytmp3:
        containers:
          app:
            image:
              repository: ghcr.io/alexta69/metube
              tag: "2025-01-16"
            env:
              DOWNLOAD_DIR: "/downloads"
              STATE_DIR: "/config"
              YTDL_OPTIONS: '{"http_headers":{"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0"}}'
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8081
    persistence:
          config:
            type: persistentVolumeClaim
            size: 1Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce
            globalMounts:
              - path: "/config"
          output:
            type: persistentVolumeClaim
            size: 8Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce
            globalMounts:
              - path: "/downloads"