apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bluesky
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.middlewares: networking-cloudflare-only@kubernetescrd
    cert-manager.io/cluster-issuer: letsencrypt-production-internal
  namespace: kubevirt
spec:
  ingressClassName: traefik
  rules:
  - host: ${INTERNAL_DOMAIN}
    http:
      paths:
      - backend:
          service:
            name: bluesky
            port:
              number: 443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - ${INTERNAL_DOMAIN}
    secretName: bluesky-tls