---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app authentik
  namespace: flux-system
spec:
  targetNamespace: security
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/security/authentik/app
  dependsOn:
    - name: external-secrets
    - name: longhorn
    - name: traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets