---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app affirmations
spec:
  interval: 1m
  chart:
    spec:
      chart: app-template
      version: 3.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
    timeout: 10m
  upgrade:
    timeout: 10m
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    controllers:
      backend:
        containers:
          app:
            envFrom:
              - secretRef:
                  name: affirmations
            image:
              repository: registry.home.${INTERNAL_DOMAIN}/affirmations/backend
              tag: latest
            ports:
              - name: http
                containerPort: 8080
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            # probes:
            #   liveness:
            #     enabled: true
            #   readiness:
            #     enabled: true
            #   startup:
            #     enabled: true
      frontend:
        containers:
          app:
            image:
              repository: registry.home.${INTERNAL_DOMAIN}/affirmations/frontend
              tag: latest
            ports:
              - name: http
                containerPort: 80
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
    service:
      backend:
        controller: backend
        ports:
          http:
            port: 8080
      frontend:
        controller: frontend
        ports:
          http:
            port: 80