---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeadm-control-plane-hd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: longhorn
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kubeadm-worker-hd
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  storageClassName: longhorn