apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dynatrace-api-key
  namespace: dynatrace
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-talos-prod
    creationPolicy: 'Orphan'
  data:
  - secretKey: apiToken
    remoteRef:
      key: kube/dynatrace
      property: apiToken