apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ipwhitelist
  namespace: networking
spec:
  ipAllowList:
    sourceRange:
      - 10.0.0.0/8
      - 127.0.0.0/8
      - 172.16.0.0/8
      - 192.168.0.0/16
    ipStrategy:
      depth: 1