# Sets the maximum request body to 2MB
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: request-limit
  namespace: networking
spec:
  buffering:
    maxRequestBodyBytes: 10000000000
    maxResponseBodyBytes: 10000000000