apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: open-webui
  namespace: self-hosted
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: open-webui
    creationPolicy: 'Orphan'
  data:
  - secretKey: OAUTH_CLIENT_ID
    remoteRef:
      key: kube/open-webui
      property: OAUTH_CLIENT_ID
  - secretKey: OAUTH_CLIENT_SECRET
    remoteRef:
      key: kube/open-webui
      property: OAUTH_CLIENT_SECRET
  - secretKey: OPENID_PROVIDER_URL
    remoteRef:
      key: kube/open-webui
      property: OPENID_PROVIDER_URL