---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: *app
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: *app
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ollama:
      enabled: false
    # -- A list of Ollama API endpoints. These can be added in lieu of automatically installing the Ollama Helm chart, or in addition to it.
    ollamaUrls: ["http://ollama.${EXTERNAL_DOMAIN}:11434"]
    ingress:
      enabled: true
      class: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production-external
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: |
          networking-cloudflare-only@kubernetescrd,
          networking-request-limit@kubernetescrd
      host: &host "chat.${EXTERNAL_DOMAIN}"
      tls: true

    persistence:
      enabled: true
      existingClaim: "open-webui"