---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  chart:
    spec:
      chart: traefik
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      version: 34.5.*
  install:
    crds: Create
    remediation:
      retries: 3
    # createNamespace: true
  interval: 1m0s
  releaseName: traefik
  targetNamespace: networking
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    additionalArguments:
    - --serversTransport.insecureSkipVerify=true
    - --log.level=DEBUG
    deployment:
      additionalContainers: []
      annotations: {}
      enabled: true
      initContainers: []
      podAnnotations: {}
      replicas: 3
    globalArguments:
    - --global.sendanonymoususage=false
    - --global.checknewversion=false
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        redirections:
          entrypoint:
            to: websecure
            scheme: https
            permanent: true
      websecure:
        tls:
          enabled: true
        forwardedHeaders:
          trustedIPs:
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
            - 2400:cb00::/32
            - 2606:4700::/32
            - 2803:f800::/32
            - 2405:b500::/32
            - 2405:8100::/32
            - 2a06:98c0::/29
            - 2c0f:f248::/32
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
        proxyProtocol:
          trustedIPs:
            - 173.245.48.0/20
            - 103.21.244.0/22
            - 103.22.200.0/22
            - 103.31.4.0/22
            - 141.101.64.0/18
            - 108.162.192.0/18
            - 190.93.240.0/20
            - 188.114.96.0/20
            - 197.234.240.0/22
            - 198.41.128.0/17
            - 162.158.0.0/15
            - 104.16.0.0/13
            - 104.24.0.0/14
            - 172.64.0.0/13
            - 131.0.72.0/22
            - 2400:cb00::/32
            - 2606:4700::/32
            - 2803:f800::/32
            - 2405:b500::/32
            - 2405:8100::/32
            - 2a06:98c0::/29
            - 2c0f:f248::/32
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16
      metrics:
        port: 8082
        expose:
          default: true
        exposedPort: 8082
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
        allowCrossNamespace: true
        enabled: true
        ingressClass: traefik-external
      kubernetesIngress:
        allowExternalNameServices: true
        enabled: true
        publishedService:
          enabled: false
    rbac:
      enabled: true
    service:
      annotations: {}
      enabled: true
      externalIPs: []
      labels: {}
      loadBalancerSourceRanges: []
      spec:
        loadBalancerIP: "${TRAEFIK_EXTERNAL_IP}"
        externalTrafficPolicy: Local
      type: LoadBalancer
    metrics:
      prometheus:
        enabled: true
        entryPoint: metrics
        service:
          enabled: true
        serviceMonitor:
          enabled: true
    tlsStore:
      default:
        defaultCertificate:
          secretName: external-default-tls
    # logs:
    #   general:
    #     level: DEBUG