---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.10.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: authentik-secret
      env:
        - name: AUTHENTIK_POSTGRESQL__HOST
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: HOST
        - name: HOST
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: HOST
        - name: AUTHENTIK_POSTGRESQL__NAME
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: DATABASE_NAME
        - name: AUTHENTIK_POSTGRESQL__USER
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: POSTGRES_USER
        - name: AUTHENTIK_POSTGRESQL__PASSWORD
          valueFrom:
            secretKeyRef:
              name: authentik-postgres
              key: POSTGRES_PASSWORD
    authentik:
      redis:
          enabled: true
    server:
      autoscaling:
        enabled: true
        minReplicas: 2
      # metrics:
      #   prometheus:
      #     serviceMonitor:
      #       enabled: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: letsencrypt-production-internal
          traefik.ingress.kubernetes.io/router.middlewares: networking-ipwhitelist@kubernetescrd
        hosts:
          - &host login.${EXTERNAL_DOMAIN}
        tls:
          - hosts:
              - *host
            secretName: authentik-tls
    worker:
      autoscaling:
        enabled: true
        minReplicas: 2