---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.10.0
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: &secret authentik-secret
      postgresql:
        host: enterprise-postgres-rw.databases.svc.cluster.local
        port: 5432
        read_replicas:
          "0":
            host: enterprise-postgres-rw.databases.svc.cluster.local
            port: 5432
    authentik:
      redis:
          enabled: true
    server:
      # autoscaling:
      #   enabled: true
      #   minReplicas: 2
      # metrics:
      #   prometheus:
      #     serviceMonitor:
      #       enabled: true
      resources:
        requests:
          cpu: 30m
          memory: 400Mi
        limits:
          memory: 800Mi
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: letsencrypt-production-external
          traefik.ingress.kubernetes.io/router.middlewares: networking-ipwhitelist@kubernetescrd
        hosts:
          - &host login.${EXTERNAL_DOMAIN}
        tls:
          - hosts:
              - *host
            secretName: authentik-tls
    worker:
      # autoscaling:
      #   enabled: true
      #   minReplicas: 2
      resources:
        requests:
          cpu: 30m
          memory: 300Mi
        limits:
          memory: 800Mi
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_POSTGRESQL__USER
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_POSTGRESQL__PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_POSTGRESQL__NAME
      targetPath: authentik.postgresql.name