---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.12.3
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    global:
      deploymentStrategy:
        type: RollingUpdate
      envFrom:
        - secretRef:
            name: &secret authentik-secret
      postgresql:
        host: enterprise-postgres-rw.databases.svc.cluster.local
        port: 5432
        read_replicas:
          "0":
            host: enterprise-postgres-rw.databases.svc.cluster.local
            port: 5432
      redis:
        host: "{{ .Release.Name }}-redis-master"
        password: ""
    authentik:
      redis:
        host: dragonfly.databases.svc.cluster.local
      email:
        use_tls: true
      log_level: "debug"
    server:
      # autoscaling:
      #   enabled: true
      #   minReplicas: 2
      # metrics:
      #   prometheus:
      #     serviceMonitor:
      #       enabled: true
      resources:
        requests:
          cpu: 30m
          memory: 400Mi
        limits:
          memory: 800Mi
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: letsencrypt-production-external
          traefik.ingress.kubernetes.io/router.middlewares: networking-cloudflare-only@kubernetescrd
        hosts:
          - &host login.${EXTERNAL_DOMAIN}
        tls:
          - hosts:
              - *host
            secretName: authentik-tls
    worker:
      # autoscaling:
      #   enabled: true
      #   minReplicas: 2
      resources:
        requests:
          cpu: 30m
          memory: 300Mi
        limits:
          memory: 800Mi
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_SECRET_KEY
      targetPath: authentik.secret_key
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_POSTGRESQL__USER
      targetPath: authentik.postgresql.user
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_POSTGRESQL__PASSWORD
      targetPath: authentik.postgresql.password
    - kind: Secret
      name: *secret
      valuesKey: AUTHENTIK_POSTGRESQL__NAME
      targetPath: authentik.postgresql.name
    - kind: Secret
      name: *secret
      valuesKey: HOST
      targetPath: authentik.email.host
    - kind: Secret
      name: *secret
      valuesKey: FROM
      targetPath: authentik.email.from
    - kind: Secret
      name: *secret
      valuesKey: USERNAME
      targetPath: authentik.email.username
    - kind: Secret
      name: *secret
      valuesKey: PASSWORD
      targetPath: authentik.email.password
    - kind: Secret
      name: *secret
      valuesKey: PORT
      targetPath: authentik.email.port