# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: it-tools
#   namespace: flux-system
# spec:
#   targetNamespace: tools
#   path: ./kubernetes/apps/tools/it-tools/app
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-operations
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substituteFrom:
#       - kind: Secret
#         name: cluster-secrets
#       - kind: ConfigMap
#         name: cluster-settings
# ---
# # yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: it-tools-config
#   namespace: flux-system
# spec:
#   targetNamespace: tools
#   dependsOn:
#     - name: it-tools
#   path: ./kubernetes/apps/tools/it-tools/config
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-operations
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
#   postBuild:
#     substituteFrom:
#       - kind: Secret
#         name: cluster-secrets
#       - kind: ConfigMap
#         name: cluster-settings