---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-token
  namespace: cert-manager
spec:
  refreshInterval: 30m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: cloudflare-token
    remoteRef:
      key: kube/cloudflare-credentials
      property: cloudflare-token
  - secretKey: SECRET_ACME_EMAIL
    remoteRef:
      key: kube/cloudflare-credentials
      property: cloudflare-email
  - secretKey: SECRET_DOMAIN
    remoteRef:
      key: kube/cloudflare-credentials
      property: cloudflare-domain
