apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weatherbot-secret
  namespace: in-house
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: weatherbot-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: BOT_TOKEN
    remoteRef:
      key: kube/weatherbot
      property: BOT_TOKEN
  - secretKey: API_URL
    remoteRef:
      key: kube/weatherbot
      property: API_URL