apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-secret
  namespace: media
spec:
  refreshInterval: 8h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: prowlarr-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: PROWLARR__POSTGRES__HOST
    remoteRef:
      key: kube/prowlarr
      property: PROWLARR__POSTGRES__HOST
  - secretKey: PROWLARR__POSTGRES__PASSWORD
    remoteRef:
      key: kube/prowlarr
      property: PROWLARR__POSTGRES__PASSWORD
  - secretKey: PROWLARR__POSTGRES__PORT
    remoteRef:
      key: kube/prowlarr
      property: PROWLARR__POSTGRES__PORT
  - secretKey: PROWLARR__POSTGRES__USER 
    remoteRef:
      key: kube/prowlarr
      property: PROWLARR__POSTGRES__USER 
  - secretKey: PROWLARR__AUTH__APIKEY
    remoteRef:
      key: kube/prowlarr
      property: PROWLARR__AUTH__APIKEY 
  - secretKey: PROWLARR__POSTGRES__MAINDB
    remoteRef:
      key: kube/prowlarr
      property: PROWLARR__POSTGRES__MAINDB 