---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dynatrace
  namespace: flux-system
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: dynatrace
    namespace: flux-system
  install:
    crds: Create
    timeout: 7m
  timeout: 7m
  releaseName: dynatrace-operator
  targetNamespace: dynatrace
  upgrade:
    crds: CreateReplace
    disableWait: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3