---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dynatrace
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: dynatrace-operator
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: dynatrace
        namespace: flux-system
  install:
    crds: Create
    timeout: 7m
  timeout: 7m
  releaseName: dynatrace-operator
  targetNamespace: dynatrace
  upgrade:
    crds: CreateReplace
    disableWait: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3