---
- name: Migrate OneAgents
  hosts: Enterprise
  collections:
    - dynatrace.oneagent
  vars:
    oneagent_environment_url: "{{ dynatrace_environment_url }}"
    oneagent_paas_token: "{{ dynatrace_paas_token }}"
    oneagent_install_args:
      - "--set-monitoring-mode=fullstack"
  tasks:
    - import_role:
        name: oneagent
