---
- name: Migrate OneAgents
  hosts: Enterprise

  tasks:
    - name: Include  role
      ansible.builtin.include_role:
        name: reload-agent

    - name: Import Dynatrace OneAgent role
      ansible.builtin.import_role:
        name: dynatrace.oneagent
      vars:
        dynatrace_environment_url: "{{ dynatrace_environment_url }}"
        dynatrace_paas_token: "{{ dynatrace_paas_token }}"
        oneagent_install_args:
          - --set-monitoring-mode=fullstack
