---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn
  namespace: flux-system
  # labels: 
    # substitution.flux.home.arpa/disabled: "true" #don't do a sub here so we can bring in secret values
spec:
  targetNamespace: longhorn-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  # dependsOn:
  #   - name: traefik
  path: ./kubernetes/apps/storage/longhorn/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app longhorn-config
  namespace: flux-system
  # labels: 
    # substitution.flux.home.arpa/disabled: "true" #don't do a sub here so we can bring in secret values
spec:
  targetNamespace: longhorn-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: traefik
    - name: longhorn
  path: ./kubernetes/apps/storage/longhorn/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets