---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app redlib
  namespace: self-hosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      redlib:
        containers:
          app:
            image:
              repository: ghcr.io/kankerdev/redlib
              tag: 6be6f89
            env:
              REDLIB_DEFAULT_SHOW_NSFW: on
              REDLIB_DEFAULT_WIDE: on
              REDLIB_DEFAULT_USE_HLS: on
              REDLIB_DEFAULT_HIDE_HLS_NOTIFICATION: on
            envFrom:
              - secretRef:
                  name: reddit-subscriptions
            resources:
              requests:
                cpu: 5m
                memory: 50Mi
              limits:
                memory: 250Mi
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /settings
                    port: &port 8080
                  initialDelaySeconds: 20
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

    service:
      main:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: traefik-internal
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          traefik.ingress.kubernetes.io/router.middlewares: networking-ipwhitelist@kubernetescrd
          cert-manager.io/cluster-issuer: letsencrypt-production-internal
        hosts:
          - host: reddit.home.${INTERNAL_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts: ["reddit.home.${INTERNAL_DOMAIN}"]
            secretName: reddit-tls

    fullNameOverride: *app