---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  targetNamespace: immich
  dependsOn:
    - name: immich-config
    # - name: cloudnative-pg-cluster
  path: ./kubernetes/apps/immich/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-config
  namespace: flux-system
spec:
  targetNamespace: immich
  dependsOn:
    - name: external-secrets
    - name: longhorn
  path: ./kubernetes/apps/immich/immich/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
      - kind: ConfigMap
        name: cluster-settings