apiVersion: v1
kind: secrets
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:Wrvoms6jEmh1NcE=,iv:2v6ChS6/FvIOgD/+iRXksANm6Sddzx50gh4O172Wr8M=,tag:OuCYfpcgUAVxa5m76mlSTQ==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:t3vQPE5612aYFbASoVhlTHoCog==,iv:2UUoTwu6GgRZGlK6PVxw8nI0zyyhXrGO9L9uv4Gpkpg=,tag:ENmWIP8qjvKK3aA4emz8Gg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:RxB/X6Ck/bCn2uWxnCwV1FRBYZELhQ==,iv:1FfXZzgK8/HHcx/J3EmZTiYV/qiKd0oCuXdvit6DMUQ=,tag:hkVu4dJS3TwtBZJYusRSvA==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:j7cZnofl9eIcP4GJFfJ8Ou+V8K1zHyq7Z7tXJNP8LTyh7whrnmdqwaGiuvv4jZ+UCIU5u2EvhCGQJH/l0S99VsG+fnLeXxShdijd9wGxbWnJRiXgyz91BQw+4gowdC/j426UssVg0AYoS8v/4YVtuPc7/FjHRPSNlQ==,iv:lTebWgUSK7YXlFrixHiFcf9bydYs6PMeA/uYngMZ5lw=,tag:opAZ01KNsf33YpszXF1Daw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4kd2ctw6kvh58hr90gj3t6lx3fvaqgsvp0mtrk9c6wc5slmrprs092rua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidlNmRDNTZlAzdG5XTm5o
            OXVrUE5SNytkamxOQ2tCWDJhdVBCcVI0alhzClpSSW5jK0VUNWpURnpXcHlKeDFR
            YWg2dmNkSHpZK0phNlduL3J0TUdVT3MKLS0tIGYwSVdZalJNU243VkFjaWJST0tK
            TG1SSHFDRjdrU1N6dHBENUNvdGhiV2sKn5qde2fiUAfEIyaXRYEvFXaGNlAPkvJp
            Qn+FAvDEfB8uDTwVHAyjOQS9tlnvDzeIstliaMYE++FpcNUxHT63dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T05:18:30Z"
    mac: ENC[AES256_GCM,data:CE0arQ5mN/RQ89CKf6zqaW6Mml3lBsj80ymm6qZLdY6e3LEarPy+Udk1tUGUH9E11yG8yC2TDOCnwl20l7/vhN2+TCOT2WdMLLrPCYb+Q7L3/4NnDgQnMoL2hSD9tn0PTKsnNztPIm+7IM7pLjv+f1lhZbOp/kT5mY9oKH8Cq7M=,iv:LWJqCwPE2HoCQ5OG8+LF6i0AC6tE8othUgsG6dKQpYc=,tag:nnC8SbCIhAJhyes3ju+lLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
