apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:or2/6hLMGQNHOMQ=,iv:usTltRmaa/hoULSpkKQimRqML6vCrf4GAY0bzf3jQCQ=,tag:6WY/04/8qqLyvcRWT5lxXg==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:mw+0cG+oeEeJmkOmY80ooZwXiQ==,iv:MObJbRavCE7pNzn8r5tryxcH9/sH6TYW8HTBCRX9UOA=,tag:vwcTUleXxOuXQPgfkBCEIA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:OPSzh5nitfVQx+aF3WYGmm8YAaOZ1A==,iv:z+8MiO/7tPayn3gvqGF162M+DuFEV1aMGUQ6nVJcZBU=,tag:StXqEk9fLZRl52Iqd3wkWQ==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:0ZxgROkZQddzhThplrv1fLsj+lzzDUTKfAvmKPO0yCBgSFct0Z0lBMVBzVJAxC1bASEYDAOnv8LnJ8ILrGSRQLt47IKjkVSCnzgToJ2TkmGT6mGluLxegfsnL2JaWDQ2vWPyIRWWoy5I7AyBf9YIWV2K+DC8yQmdjw==,iv:iItU3TDvZtfvoua6Er9EHxDNkkJlJy73nOd2DvFIuqs=,tag:QL9eW9KaIQGfp1QKhRLk0Q==,type:str]
    DYNATRACE_TENANT_URL: ENC[AES256_GCM,data:/NZGJV1d6EdyH1LoLKm9QQmwTzholFGY4lFNeoEsdIoqWGqTCk7d,iv:upog+wyYEuYY4DRVKzI9wWlknTIJ50ynGs8jdPK+JK4=,tag:oSnhAyvIP4kM4mF8LZ9EEA==,type:str]
    DT_INGEST_TOKEN: ENC[AES256_GCM,data:a3bgI7kPksXClu7RiLQoN1kcWfbkcrtdJs0Lvs+IQlQ8VAZYVqrA9FeIwH7aF044uuVQBYVnhWDiw/voKZR6ZD+Mg6Mt4QE3kVyKuAeVSqyeAf4zNjjajFfzAiJQd5gy,iv:aKMjXu8ayEtBbAraSEvrfSEfhZ6/r52p6K82X2O6F6g=,tag:WF5CmpJfXCL3+NwufMQL3g==,type:str]
    DT_URL: ENC[AES256_GCM,data:VrKYZ5xits3mlj/zscUPMAtook0PU4Bdq802,iv:ni7k7JXpziBf+dZcl7qRfvsx/FUpfweMBSv1YxFbasM=,tag:IZYY9qdL6Dlmk8Cyu/aNMw==,type:str]
    FLUENT_CLUSTER_NAME: ENC[AES256_GCM,data:iiFLuzjezWAzjaA3bjM=,iv:i8l67kOzeqgLRfce1vKajPEZ8vYqgHLnquz5IMJAl98=,tag:e0YyoQvDLDKhq/kL4uBarg==,type:str]
    EXTERNAL_CNAME: ENC[AES256_GCM,data:YyEfao2gPfQGT1UyQ9Iav6PifybOA4jYWug=,iv:J1/mntpIU2STB9P5vYT9sdSQ2IcQI2yymoaLSwl9C0c=,tag:jw1yrPFrQlEu0hQ+C8eSAA==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:EJDWrQ1e60WZNm4SwqeO,iv:QtXhQGH8UZ9v9xByD4QBVQ6T7Lsvkz4HeHlIkN2k1Ag=,tag:8rvN9QWiKjZdLi/o7RqmXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4kd2ctw6kvh58hr90gj3t6lx3fvaqgsvp0mtrk9c6wc5slmrprs092rua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Z2E0Tm1JL0NsMUh6OHVv
            MUdPTVQycW9pU2JYTDM0WklxRnBrUEx4Q0hRCmtFV2trS1VEbDBkNElOeWhvSlFX
            VzVIVFNWYXp5Tyt0eUk2TTF4Z2E3MWcKLS0tIGRzN0FHa0liUzMvZDRSTnJUYk1G
            clJscDhUcUNMUS9mUC85TnNLRHNXNncKaRABuL3dipTXLSZv96tSJmZ6f34wqWKv
            9ARQPkJyJvirKwp3IYg8bs5shf0V5BSYTHvIAZ8Ms/dGRg94c1r/Rw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T08:53:39Z"
    mac: ENC[AES256_GCM,data:PbMcVmV/Dp+tATEvASUOOmReZTvCD1jWU3pLe546gffBaUi16PfXplJLQs2ViyMYfzBksdd61eX9+KYSqoHGc+8FCSReTUO92vOukd7hSBP+HEYCIghkgKZWt60i6bJHTG1p0tAIbsxm4jpltp5baJTU7SMQOZZ6V0nB77HjOy4=,iv:f9qM0nBhz5MKFcAUtU2P5+m95A1HYpbIHgFZlsR1Z5s=,tag:QVHJWrMCREfjwCFLrgWbig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
