apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:HUkpNvAtGTKhjhQ=,iv:Q5qCnawgytmRl6AFVYD9ccmwj/RsvoUdAVaNxZ+QhsI=,tag:D9QDpJ/+uWs4/QHwv7OFDw==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:lSPMxLCBhyXMwhj2nnntDdfNFQ==,iv:3VDliFClABWokLoV87oS3e3Bbbml4zBVJCb3FBuaQUg=,tag:5RamLGuFP2BiJ3HHi1mhkg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:Ejt5XM2qrKN5kkKqv8alQvBf6EovRQ==,iv:+SI1OokI+wLX9CLQu4tIBSbO5FEyZyLIYaasnCz7yzk=,tag:RtFbsbFrq9coSzk0MhNAzg==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:s0fSjPTDxc3tW8ZNjT58qbOfq1vvIAzq56qvlLofdTF0JfQERfe+czeE3Q0A0+R6ppG/74UyxRysDRjgCr5DLLW42rpVMd1lGxyhYOWpKBkQToPHyrteY/B6bSrB8H8KOPpohNp4Xl11vHYaS7x4hme4QEQpiY3n7g==,iv:LttLh1B0v9rsdHE3+6B8skQPzVIxUzaFbePsnbgK6I4=,tag:l1UPhzBpOmqgUsozzgwqTw==,type:str]
    DYNATRACE_TENANT_URL: ENC[AES256_GCM,data:os+yR1KGAo1HsQIYJatDNmMMcnwrgM0FUT/+Ahu/6gQLApfQ0Rio,iv:zAA65wDx8BSeU1iGCxuWtmIBaRusdxbxhiRwG7j9i2s=,tag:1eYMwKL/oRHH1gbKHYmhuQ==,type:str]
    DT_INGEST_TOKEN: ENC[AES256_GCM,data:qDca8Emiv2v2jZBylOIBDChuW5llIwyMl7K/IY6hOFUwZs42fuzB2kIK0JFAPbJ5G7l7drP1XD71Bm0+w8VX/zsj12nzdATuC2EukKuKD15SPSzmBvzXm3rScQU+PUc/,iv:IzjFzgTWeiFpPfrDU4AnEYXXSaI+rCtgFulDTIcgFU4=,tag:B9N5ulODvXAM1NZA2LvnQA==,type:str]
    DT_URL: ENC[AES256_GCM,data:8FXuHPhEXW9oeQJ1nPf4eM8gnDpRYiW/GBWA,iv:kf6cJLU1wV3/o4paLf083hwEiYhE6Li0QwMmadwhW7E=,tag:t+nSZiVbpPIaVkXus6PpHA==,type:str]
    FLUENT_CLUSTER_NAME: ENC[AES256_GCM,data:3F6w2QkOIVdDfGLaNtk=,iv:HNeKXdTQR7VO/AK6GdAp6axnlhIDlGL+qeY/p8QDXu8=,tag:9e62/5WkuWTyWYo7xKuQrg==,type:str]
    EXTERNAL_CNAME: ENC[AES256_GCM,data:lqVpikOY1e0iFBRr3uKf9+XYTQWf1ezVyuM=,iv:Qqzx2laaUt8RIK5V8s4WIyEXCUKRUscYlFY/TEfpVoA=,tag:KniZlbtojnNZbJkldOGeUg==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:PiyVvv2xU0dJhdolADX2,iv:HfMT84DE9LZnXXnvX8ha5ydjP6BI5GuZmOHSpfhv2Nc=,tag:d2hxTx8/4+OMf6s5U2YBkA==,type:str]
    S3_BACKUP_URL: ENC[AES256_GCM,data:FjDhp+xlksVLo5zoUikU8vTXGYUFSoIt4C+OYjdy,iv:tKjVP69VxbASrDuWTon/lAKv0E3peWtJsoTsQ/iETyM=,tag:OhmrEFCmCf9+QdpxWrDm8w==,type:str]
    NFS_SERVER_IP: ENC[AES256_GCM,data:T2EV8/wKnps=,iv:ZyH23Q5Bb43Mw8qSYNcPW1MwnlQpoEJqCO7dLfA5VgM=,tag:Zm7DuiW4DmIa1SsS37bpKw==,type:str]
    NFS_IMMICH_PATH: ENC[AES256_GCM,data:kdsFiamaoBVh3MVFUvVELgZfc12cnw==,iv:wYN8DPi3XT/2xeqoviKOeBibHUqj8xEMvghVFxNICNg=,tag:GOic8zMOmxY0aY68DQ5eaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4kd2ctw6kvh58hr90gj3t6lx3fvaqgsvp0mtrk9c6wc5slmrprs092rua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZ1pjL3dLTjNGNDY5MFh1
            U2pCOURYNTZaNHNZNE5iaXFaTnI5SVRmTEZVCkdRaHBQVS84Zi90RmV2c1l5Q2Qv
            WFBZc3JPaXloZS8veUxlMzl0SjZRWHcKLS0tIGowb05MMG42bEhndzFrRW4wWDNP
            eWYxeUMwK2Q2WEFDd052M29FeVhEekEKrcQpAaqVxCsdLdgcWvyiPoTq82wYPzfU
            L+rkR7wr0VJNsoaHtTQZn9XTbLiQZkbZNfkKNMW2CV0W/4UO/ZsLhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-15T02:43:37Z"
    mac: ENC[AES256_GCM,data:1F3AH9aisFPr1NnfJ8smHyWs/MgdPjmg6OpQj5p40EKuzIKtckflohtJZ6YhXZCxfuVA4bGiu6Te/YgAx8/eea+17UGVVIY4exWBTFzfOcyEtd/lSJO45ISQVI3U9vVDsBlrajPOrNoRJrTB2cs76wds6+g10a/GVQbUCVM3aTc=,iv:7FBlIiNMOF1EBxxUnAr4eO3I5Ya6U3C8pg5r2U/AGVo=,tag:V5HURwm95cohToPIImtWow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
