apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:sDabEBLED1R5P6s=,iv:JeAnPLyoeEyn4C33wigFcTn9q7DwIX26GNsF4w2CICc=,tag:gjek7u2FYB3HkaiHVF1xGA==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:eBZ45EuooFXJC2koElXK157YMQ==,iv:83biODWl1eTnn8NuHahEkw1jyHUyfbNMw9m0Ak0dWoY=,tag:4KWQpVSanfWVp4DYN3GheQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:TCA28X8JO8Kh5gfRPlsO+hk+j0WSWA==,iv:RC0w1M+NvfeJqBtdmOoUGHR62f5zhMZXwrC++Q9g8as=,tag:zUpGhxq9VUOrOYfA2zRDzw==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:sQu7v4sljt3HXDRMygLgNjV7QLSU30Wydq+k1NWfAioBqVius4aWIfAgorWVTFY2VfdHtcjMtmxrM3lSq44uPb0eBY1MQ+i4qdM2tDzeGSFzFmQV7bdXOlgNKWkB3kuxlj5qzT4ECcrVwd3DXuNMApqjHSDFqKIBRQ==,iv:ITB2kkIWb0Wm47YoeFQ75+iXA9UHSQ5MyTCoX8R1Tto=,tag:zEcSUs6UEAHXzobPnTdbcw==,type:str]
    DYNATRACE_TENANT_URL: ENC[AES256_GCM,data:TFqFcg+FOgqiaEhJEopPwMFmUhOXwPSYimfu8bu29GJ6U1zeNpoH,iv:InZG3ZORgYg60gJ8jFtltnSkALEPYYoFlyIph3zwu+Q=,tag:0kDHgCr5Bm8pU/y1iWfaWA==,type:str]
    DT_INGEST_TOKEN: ENC[AES256_GCM,data:wRwrmJG6PTEbse19Tgue56nK4QHrGo+78oVNHSIDlyFos3VwL+jxSFpXtLJ+mo9FdOCsDzRY5UA4D4dqPYMbcX8xeP0Oj4mgDH5+265jI0G+MOBwaaEmtCezqNXGRKYG,iv:4/NxMNWyxVlhotA5EN7yaNF1NebiZBN3Owj+CdQyUtk=,tag:y5SlmMOStI079SAYv2ryiw==,type:str]
    DT_URL: ENC[AES256_GCM,data:RHEHL5jlUJ9nGvSktnk8akPHlzIF5zmgjEz/,iv:Gh6IWDuBSZ+bMDIPqhMLhGYaJ4HA4Gmi+bW7hETax9s=,tag:NdVUADncHpTxo28fH+ex1w==,type:str]
    FLUENT_CLUSTER_NAME: ENC[AES256_GCM,data:wmAZj2ZQliXNMo3Iiek=,iv:X5Ur1OBE3e5258nvu6aqMVbqf3f4yfr4VE9M3i2z2YE=,tag:uqdadmADmPWcfMcI5KH1fA==,type:str]
    EXTERNAL_CNAME: ENC[AES256_GCM,data:l/aHwypcJ8BbB1fOL3KIE3r9hwUNBIUllXg=,iv:4AS2/r9Hr37IGFUX3bNS+GSmK2I5u9N+uzG9p3eItIc=,tag:0Is7Cz24wWSjmeFqs6uSnw==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:3voLawlpUPtLrqq8+3DH,iv:c7WSwdFvZRQTrBBfVNvvxkxVM+Kx2RX2prYQ14TyKMY=,tag:0wy3fbVmVBqow10CVqWykQ==,type:str]
    S3_BACKUP_URL: ENC[AES256_GCM,data:O8hyCbiw2P1m1gHJxlIwiTAKmufhLAe7BFb967cj,iv:ew2/vr5zsLjc4GgOioCSndblb/42u8+6bEOTiWI7yzI=,tag:jZTtw8D54x569vcXmcRl6w==,type:str]
    NFS_SERVER_IP: ENC[AES256_GCM,data:i0Wa89INT8g=,iv:kSz69eYbuqjYNWDDQKcdOEyiO9AdEeBjmjG8jUWOgGc=,tag:aygJm3V2JuPeojeSvujDAg==,type:str]
    NFS_IMMICH_PATH: ENC[AES256_GCM,data:j4p8Rh67kEKHtdbJhQuFjAHxTh3zkQ==,iv:Enat+Ew6Zu7c0DIZaBL06pCmgUjvabSXVTf9zIXgb3M=,tag:APlLriKrSfslAeIUtZV7CA==,type:str]
    NFS_DOCUMENTS_PATH: ENC[AES256_GCM,data:fOag/iRmQML0GKxmssx25rguDf12OKv9Vw==,iv:erb2jkS6HnqjlPOVhv6XncQo6hemqSJ2Czo3v4Dq01w=,tag:nv7G6/JRO0dcy2urcoDnsw==,type:str]
    NFS_POOL_PATH: ENC[AES256_GCM,data:70m4Va52Q0V4XpN5m08Pxg==,iv:qftyFDDpfF/x5IiDu/igYtHHArzwQ6JxSX9NMqGE9Wc=,tag:kjCEJyqFWcIA7pOOADs20Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4kd2ctw6kvh58hr90gj3t6lx3fvaqgsvp0mtrk9c6wc5slmrprs092rua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbzc4VlFQSm95aG5GZThO
            VFVGNXAwNDdqdmhBWTI1dzNtR09EOW1OOHlrCnZPeXlvdFFPR3JMMUF4WDBQVDRy
            dEVDemhMd1ZoZk1pRkR3RlhRbDV2cGcKLS0tIGZwZHdSODlnWVNHbjFxUEczM2F2
            clFlbDU3VTMxemVuSkZiTmdFYSswekUKknmJa+SuWFiQ8j+R9x5Y/Xhx3rJcpwws
            qbNyAHASnhoWnYyxodik4hM2OaBz3v3p0ng3knHANQrvX5GhdegwqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-15T04:58:24Z"
    mac: ENC[AES256_GCM,data:JJJfzlX5dCkZDrzFG8GVDl2YVnxw5UPZu9uPlFoFetZ99acF+02zc0MzdbyEgrO8GvupKIeWv7WjRQC8SrYGo9E9LmO+tPgh9F6KpJS6z7kydXdW4Oqd89S/2bfQLua4RwzMJkAcp056xuPCVseT21KpWLYvnIej6KJ+ek1OEcc=,iv:lPOO2YDNibvLvOCGQJALYnDM/h3h6mi0bSaSo82KEGk=,tag:wtNcJ3TgE27nGRqtJFyMRA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
