apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:Mqe4s/ZeUqPSJmQ=,iv:TNnkfTnq1pBpk/5xbADgIyHmVGDzBYFuNiagyPbabxc=,tag:zh3qVzhiAz+iIP2aD618hQ==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:eH+qRrw5ZJfxMmfa/ID6u3ugEA==,iv:Y4dUN68xoNo63DcIn27So41eOTCRc/Q32Xh0YN7AXz4=,tag:Hvu0pzsw76wKbUx+OSP9cw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:/mVefzxVvzFVm9+RjdsDF0bNncCfhg==,iv:WfUSck40yKejv5/BOd5Tu6IAyrM/qcUBQH8QJntBIfI=,tag:H5Trv1hgs4Vj0nGUzApP6Q==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:/ohF78uwZ24t2Db4Y6HvmBwgAzVgzCUGnMVlqo5X3aiPp1T6Q0MTzj5hQWuWjqOyc2WN6v/UcheFVFueujntQQwElVsu7n35jH2aihlbL2Pnp5nELxs4uH1ofDlVaIPjztppkBAufKeeMu7KTqmNbBQcjgiuglxwug==,iv:jcq+I80k0DED4djcCwavEF0WHCUZz5/1umHoNhA/X9s=,tag:BOQAmLETzMCfxm/gUMEdTg==,type:str]
    DYNATRACE_TENANT_URL: ENC[AES256_GCM,data:EpxUZss5fnBzVMpwXvb/h8uswcWHp/TiVahltT7E92u2sz5a6wzFtwNjtemX,iv:Jy/4ShwLB1s44f8X3pMzrOHvni7kpzs7Oy6SelYlehI=,tag:Pam64XytBjnvFLEsxPSx+w==,type:str]
    DYNATRACE_REPO_URL: ENC[AES256_GCM,data:orN2Qq+yniC1kLC7Zc+NabVZyJVupfpVHCN7Oea6jl6g+If8Ye2XO1N8MpEjMt3LgGU8lmk=,iv:sfBcy0VHZ+zZn6iOsW9uuF6sgqPOKXLjY+EuWcaNl1E=,tag:uSdj9nRL/YH6iSKh3mD+aA==,type:str]
    DT_INGEST_TOKEN: ENC[AES256_GCM,data:ll0rLi/tvTNTDk4QlMkHLmM2fkNRIyuyR6p/ZhVdSmmu57TSOEfP6zfrTZYNtA6Vio0LbUajGzjxloHKQv4Cgb2xVNWeCmEZcpPsStnBTicYAipr4rawCoO2nACuK1Br,iv:rAaeB9lYzovNsGlBeZjNw2fjEu+paBrYt4Vb+pnOIJc=,tag:KJmMRpdnDWpbp48UY7DLBw==,type:str]
    DT_URL: ENC[AES256_GCM,data:bX+5i9oHDV7YQolYDAHUkkt9+CXA5qVrxDLV,iv:3QfaIFl+3CI5bW6Ou8ZllbQtQWrLWkTaJzj8CwTImS4=,tag:S1daQqcoXEETe73ycmYBjg==,type:str]
    ACTIVEGATE_TRACES_URL: ENC[AES256_GCM,data:3wLhmZQ1XWBrmpIF0M+lQ+O3TPL4IdtU8uji6hpdUuKprErr2TAelwG5WHf145XUGnTPVTAN24mNwTX9kgb+7xls,iv:2z+nM8ymN6pMlJ2A0o5PmtMBQZnhmbwSjaUrsgZqPDY=,tag:nOG4yzOKfqPWrGfO+1vZ+A==,type:str]
    FLUENT_CLUSTER_NAME: ENC[AES256_GCM,data:BNI7Rayo9AnCIM9P22A=,iv:wcLN/dSGAcdetJldULyc0DoyGDsn+Sf0nR875orDzSs=,tag:gblxKWZS3DBj2wgtanfSlw==,type:str]
    EXTERNAL_CNAME: ENC[AES256_GCM,data:RU8Dox0oIM6aMNZMBt7hmO3BpEz72qW0LsI=,iv:5ZYAE7yhyvG43Ua9xLdbVZcwH5QkikcP9ltAH1YIgGE=,tag:UAt8uKMfsIHKnX+G1XHQpQ==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:2USYpN3DAsKeSHcwGFvx,iv:r0goAMCxW/g6YS7txenM2OBpfvXN71H57iZibBxfMMs=,tag:o/VcslVZuNwGCgk88D86Yg==,type:str]
    S3_BACKUP_URL: ENC[AES256_GCM,data:CEo8iQ5M79oG0PcHrTTT7hvWPRR5pa62qQ2yvfCR,iv:cySDIsO9d7Ae3C5X/DwYH46FyJAm2K2wHpdU2y2ugqk=,tag:BMlXjouvSNdG2+1Ql5DXUw==,type:str]
    NFS_SERVER_IP: ENC[AES256_GCM,data:aR1AljjNc9M=,iv:GKEdOutztXB7lKDM/1v33jM41+Lriap0wyecq+5RfQY=,tag:YEo/gTvK+j5ECiEW69xctw==,type:str]
    NFS_IMMICH_PATH: ENC[AES256_GCM,data:rGtC5MnHbcKAWWDC0tgX5Z5CEFcSFA==,iv:+Yg4zhJiJxEsiuapf120U8zaqQo+Us+Ms2GSy6e9FPw=,tag:r4AK3tL0565kysXg6Gie2g==,type:str]
    NFS_DOCUMENTS_PATH: ENC[AES256_GCM,data:6+weZqlxoF/IIIkPiy45w/10vNhPGuUDuA==,iv:EIpP6iPVeCSSIY0Hzg5kHwqilPN2omqW4quGU9XyIIg=,tag:/LcDrxbjxBGbuWzqYbRisg==,type:str]
    NFS_POOL_PATH: ENC[AES256_GCM,data:UdBiowkMiR+/MctVSSccoQ==,iv:lJxDVC+axIFqKxQAF2ua5S4ZiW8JomlVOaathXs9MkM=,tag:IijEAmjBdTDtqtoOyuiL2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4kd2ctw6kvh58hr90gj3t6lx3fvaqgsvp0mtrk9c6wc5slmrprs092rua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbnFXa3dKMWw4THdRVXlU
            dDJ4TlRnN3hUaFlFVWVIdG1tVWViWmx1TEI0CnFuYk9aNTdnN1BYNjl6WktjT2RX
            bFltalBzUGp4a1JYU3pucDA5R3ZmT2sKLS0tIFpsVnRoZWVLV0F1MEVTZjNEaC9U
            K0hlaUlpbmtIY0o3ZFRWYmh5NzhBZHcKYAqK79zS87MwG1vk99Icaj2HvYNXLQUu
            /qIJvcHPbKwaOaWEQctLk3mdndRlKSgnfltMJ8SR3qxF8xF94UdJ6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-21T13:20:18Z"
    mac: ENC[AES256_GCM,data:WPqbQYK+lgHzAXPgRmLbZqVn17oKfH1X3NMOZYE8PEL/VWhSKOnupk9m+yvgSIGjHTrfvFuyEqBW0L6BLlZEROYEkNn17ovK0CL78dIR00DO+GOy1VzSvlBXsIensfPCTgVtvTD1xQIH1BLVdx/hHZ1yRXRkh3GkFnZEUuGaHNk=,iv:MD9r4NGBn8YZwpe6dFactbNlXyPdJ8HzoK0UNk5aBbo=,tag:TYGzJ8rmssQuR0iX+TtdSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.0
