apiVersion: v1
kind: ConfigMap
metadata:
    namespace: flux-system
    name: cluster-secrets
data:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:s1G+xYHkps0omXs=,iv:fOYfZ0PxfdpM33bZdIHaEyXeq0Bw2d1yMP4i/TC/Tho=,tag:0xbIxBHLIRwFjAgkX2e2kQ==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:U2jAYeD/8OvHxhSF4wFraopeqg==,iv:ozLypWfKJ7fAGozGxyoqz2o7bsu+ql27beKkfvOHB4s=,tag:2mi7vWyfcxBed+L7fX1eeg==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:YPDWx3bKI/wypFSqpzHQe0wrEy3hLKY6HMWXVNA9cHY97uOrDv4b5NaAoje5D+NQIhi6YDhqndmgq3Ql65i3/NonnJ8s6wuFDAOgaMEYy6uEV8LdMISgCDDqsvbpaOXXG2FOyDRDpUePaO8mTYeblK14fhBNf7Qhdg==,iv:YZBN57CracaUO72Qi8XbDbOHYHuCs4KkH58zMfClu2c=,tag:dHAGxKqkUVFmgdTCoYBTlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4kd2ctw6kvh58hr90gj3t6lx3fvaqgsvp0mtrk9c6wc5slmrprs092rua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR2dSYzFDSmxhcUtnQ0dC
            K1NvZ0ZCWk9hZStCdHN4WFFYOUFMWkJMT1U4CnBQaDF3b3ArQURTcDFEbFdacjYw
            aVVWUDdwenRVd1BZR2pFanBhdHZtNFEKLS0tIFB1bFlrUkZxMEI4QWxRU2IrU0lh
            MkFaR3ZCS1BzQWlNQ1RRdkFWZUxjNW8K3YysdBiUW8KCv3OmKBxqM77Gacvw264N
            pgx6ZKcEfjnL1nCZEPDaji1GTeK3q1YdeKipq5xnBs31dMHOvhOg5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-07T01:17:23Z"
    mac: ENC[AES256_GCM,data:9P1D5J+nuR+zcVW7MKGSwpz2T3yjbwqxv6yzR2Hg/p+168kjFHPJuE13lMI48YUgo0FwHkhm7B8CBVcezgFWlNPItW9Q34sl8n+2XqQUKpfXbyliLLDZ5WzenHPy5QoxUBlJrjAsAskRR4Qgmi+cwFU5f25wcUbUMFRmyahhZ5U=,iv:Hb9MADxi401g02V6wkzsQehRaKszwKq/0qHUXG+w64c=,tag:z7RrlM/xyObO9ZoRjE8i7w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
