apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
stringData:
    INTERNAL_DOMAIN: ENC[AES256_GCM,data:BBiNZAvbvviIX+Y=,iv:h5Ruq9j0curtW3DYdmE/S0PX7sapqcFKKYJwqb9U+Fo=,tag:Yh6R10UJrIOlFxu3mZ+eOw==,type:str]
    EXTERNAL_DOMAIN: ENC[AES256_GCM,data:V3h4P4wukutlOzdonN+c/7gAPQ==,iv:5jDZB4QgpqjhRJiGSlO4n+KxTTZbKrW5JI4WE+LXBNw=,tag:Xp3rgrBOPUBMnAv4c7SiVw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:nAJSlpeOA+WDQpOci3WObnkTnIsRCA==,iv:LlLtaClFt+uX65Ln0z7xVGD4c5NFBKpxnkNHiT/W2ik=,tag:xzgGuXaeKm+/0nryjktuEw==,type:str]
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:Vw8wkfJEe/2TzVOliyotqkF0W20pQH15pGVzQQeQv7c8WhjNe4SwDosEHHWth1OHMIo7wOE7mZ2V3kDd1+8XXRpFmmEdgF2+UHp98NZe/T/KFWMewScQt43bFqFDCYYlKdZE/r7/p29lKQa3VAdjyhuGHlRcM4TS0Q==,iv:PFnuVemZGmxOwPgk4RAtWqnmY9yXtY12OeViXVExdaI=,tag:0IauJisDnJBYGPteOwJ/Ag==,type:str]
    DYNATRACE_TENANT_URL: ENC[AES256_GCM,data:vE9o66l+mxK2bItObH1IsB7VVER5CUINnU6CUm6Rm8CllMc/g3p9,iv:e7bIYPYnM+bIE0T9LHCUD2vQe4LQgrfqJ+39ckr6Bns=,tag:2fko3Hc+EJJWoNbsY+tuyA==,type:str]
    DT_INGEST_TOKEN: ENC[AES256_GCM,data:Yw4u/4YpuklrcmbaZluJMTqK2iYjJA3EyjSFpOEdBDXfXzYl6metnspRPzstdc0xjpZ6sEQM1pnog0b9assPRWoAqb9hjMcm14A+4OyfhDduIpVSaTZlVSDVHblSFGSJ,iv:cj/85KCVVj8WKc843/RJ4fMgZyvb+h8om69o21WACgY=,tag:vOSb2WhLrPIyEWFYtrD4Fg==,type:str]
    DT_URL: ENC[AES256_GCM,data:Rzg++zdeIcABmALEcTiAgQmpu4sRyR+IBeri,iv:a2rtDl9FSnFErGKTvtqp9lACiZfQqs5snw0ebkHMwBs=,tag:jTr8PA2IRSxuxNqRJ/Cjww==,type:str]
    FLUENT_CLUSTER_NAME: ENC[AES256_GCM,data:bNpkXBlwnBnVAYtGmVU=,iv:Kgob5rIPgPvdmY9K2vlaFnd+TgWJLDsI4ECqMU4eq48=,tag:nMwpKYkXYjjTmB/3Lzryqg==,type:str]
    EXTNERNAL_CNAME: ENC[AES256_GCM,data:PrVuZfswlvkOKzhs6M5Hmd4eTJe4Y7+NgLA=,iv:2nOGdaodVsoC7vC7DKehneFGZfYlUbyo3qpCN1fS7K4=,tag:N9DYPl99jj26AhDycDkNhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1s4kd2ctw6kvh58hr90gj3t6lx3fvaqgsvp0mtrk9c6wc5slmrprs092rua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJVHlpY09BdFpFelh1bkx5
            S0trNGUzaG5BUG9RdjRPbXhFNGRzOThrUTFBCit5a0xwcENQTCtnZUJCbUE1MG1C
            WEtzaCtxQ3pWWHQvQ1djd3ZjUkhFUFUKLS0tIGZOUlh2RnNVTTY4RGxJRmhaSzhB
            ekZhRkoyZHczNVIxbE9BQjdYbmRLYW8KDCsiUrkEoYHfTgLzAzgaTax+xkjeQtam
            ymZfhTI1g22YZp0cnR/Fh7fnOZd/QivK7FvmhGWk9jP8pXr/YImnqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-30T07:50:21Z"
    mac: ENC[AES256_GCM,data:NBx2aoJa++sn0F61xEa1tbCu/Eai5GjMVHuhgVAc3R5OD46baObL0qUFEIQBLOV07O2vdHwqHNPFufRt+viRpUJbwbGBERQp9ieTvgzXST43faLhKzH/cuR+nYTEweIW0p+g3heu3qzU+lIKMFKNGXOjdVOQ9ylDHeVAQx9TdZg=,iv:84FDLf/c7QgQ3vtYICK4Q66owPGypNNilLO4pf0843M=,tag:47Pg/FH1xxW22wcsakBYWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
