---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: flux-system
  name: cluster-settings
data:
  TIMEZONE: "America/Detroit"
  TRAEFIK_EXTERNAL_IP: "10.0.4.60"
  TRAEFIK_INTERNAL_IP: "10.0.4.70"