---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keda
  namespace: flux-system
spec:
  chart:
    spec:
      chart: keda
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: keda
        namespace: flux-system
      version: 2.*.*
  install:
    crds: Create
    timeout: 7m
  interval: 1m0s
  timeout: 7m
  releaseName: keda
  targetNamespace: monitoring
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3