apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-secret
  namespace: immich
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: immich-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: DB_HOSTNAME
    remoteRef:
      key: kube/immich-secret
      property: HOSTNAME
  - secretKey: DB_USERNAME
    remoteRef:
      key: kube/immich-secret
      property: USER
  - secretKey: DB_PASSWORD
    remoteRef:
      key: kube/immich-secret
      property: PASSWORD
  - secretKey: DB_DATABASE_NAME
    remoteRef:
      key: kube/immich-secret
      property: DATABASE_NAME