apiVersion: v1
kind: PersistentVolume
metadata:
  name: photo-library
  namespace: immich
spec:
  storageClassName: nfs
  capacity:
    storage: 1T
  accessModes:
    - ReadWriteMany
  nfs:
    server: ${NFS_SERVER_IP}
    path: "${NFS_IMMICH_PATH}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photo-library
  namespace: immich
spec:
  storageClassName: nfs
  volumeName: photo-library
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1T