---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
      version: 1.6.*
  install:
    crds: Create
    disableWait: true
  interval: 1m0s
  releaseName: longhorn
  targetNamespace: longhorn-system
  upgrade:
    crds: CreateReplace
    disableWait: true
  # values:
  #   defaultSettings:
  #     backupTarget: 's3://longhorn-backup@world/longhorn'
  #     backupTargetCredentialSecret: minio-backup
