---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      version: 1.6.*
  install:
    crds: Create
    disableWait: true
  interval: 1m0s
  releaseName: longhorn
  targetNamespace: longhorn-system
  upgrade:
    crds: CreateReplace
    disableWait: true
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    ingress:
      enabled: true
      ingressClassName: traefik-internal
      host: longhorn.home.${INTERNAL_DOMAIN}
      tls: true
      secureBackends: true
      tlsSecret: longhorn-tls
      path: /
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: networking-ipwhitelist@@kubernetescrd
    defaultSettings:
      storageReservedPercentageForDefaultDisk: 15
      backupTarget: 's3://longhorn-backup@world/longhorn'
      backupTargetCredentialSecret: minio-backup
