---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app dragonfly-operator
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: longhorn
  path: ./kubernetes/apps/databases/dragonfly/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app dragonfly-cluster
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: dragonfly-operator
    - name: external-secrets
  path: ./kubernetes/apps/databases/dragonfly/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets