---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  
  # Post Flux-Kustomizations
  # - ./calendarbot/ks.yaml
  # - ./weatherbot/ks.yaml
  # - ./affirmations/ks.yaml
  # - ./tasks/ks.yaml