apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cold-email-runner-secret
  namespace: self-hosted
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cold-email-runner-secret
    creationPolicy: 'Orphan'
  data:
  - secretKey: github_token
    remoteRef:
      key: kube/github-actions
      property: github_token