---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-tls
  namespace: harbor
spec:
  secretName: registry-tls
  issuerRef:
    name: letsencrypt-production-internal
    kind: ClusterIssuer
  commonName: "registry.home.${INTERNAL_DOMAIN}"
  dnsNames:
  - "registry.home.${INTERNAL_DOMAIN}"