apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password
    creationPolicy: 'Orphan'
  data:
  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      key: kube/harbor
      property: HARBOR_ADMIN_PASSWORD