---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-admin-password
    creationPolicy: 'Orphan'
  data:
  - secretKey: HARBOR_ADMIN_PASSWORD
    remoteRef:
      key: kube/harbor
      property: HARBOR_ADMIN_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-postgres
  namespace: harbor
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-postgres
    creationPolicy: 'Orphan'
  data:
  - secretKey: host
    remoteRef:
      key: kube/harbor-postgres
      property: host
  - secretKey: port
    remoteRef:
      key: kube/harbor-postgres
      property: port
  - secretKey: username
    remoteRef:
      key: kube/harbor-postgres
      property: username
  - secretKey: password
    remoteRef:
      key: kube/harbor-postgres
      property: password
  - secretKey: coreDatabase
    remoteRef:
      key: kube/harbor-postgres
      property: coreDatabase