---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/databases/cnpg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app cloudnative-pg-cluster
  namespace: flux-system
spec:
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg
    - name: external-secrets
  path: ./kubernetes/apps/databases/cnpg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# ---
# # yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app cloudnative-pg-backup
#   namespace: flux-system
# spec:
#   targetNamespace: databases
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *app
#   dependsOn:
#     - name: cloudnative-pg-cluster
#   path: ./kubernetes/apps/databases/cnpg/backup
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-operations
#   wait: false
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m