---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bluesky
  namespace: flux-system
spec:
  targetNamespace: kubevirt
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/kubevirt/bluesky/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-operations
  wait: true
  interval: 1m
  retryInterval: 1m
  timeout: 10m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-secrets