---
name: "Renovate"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: ["main"]
    paths:
      - .github/renovate.json
      - .github/renovate/**.json
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true
env:
  LOG_LEVEL: "debug"
  RENOVATE_AUTODISCOVER: true
  RENOVATE_AUTODISCOVER_FILTER: "${{ github.repository }}"
  RENOVATE_PLATFORM: github
  RENOVATE_PLATFORM_COMMIT: true
jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - uses: plengauer/opentelemetry-github/actions/instrument/job@v5.21.0
        env:
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
        with:
          secrets_to_redact: '["${{ github.token }}","${{ secrets.BOT_APP_ID }}","${{ secrets.BOT_PRIVATE_KEY }}"]'
      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_PRIVATE_KEY }}"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: "${{ steps.app-token.outputs.token }}"
      - name: Renovate
        uses: renovatebot/github-action@v41.0.22
        with:
          configurationFile: .github/renovate.json
          token: "${{ steps.app-token.outputs.token }}"
    permissions:
      actions: read
