---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app uptime
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      remediateLastFailure: true
  values:
    controllers:
      uptime:
        containers:
          app:
            env:
              TZ: ${TIMEZONE}
            image:
              repository: louislam/uptime-kuma
              tag: 2.0.0-beta.0
            ports:
              - name: http
                containerPort: 3001
                protocol: TCP
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi
            # probes:
              # liveness:
              #   enabled: true
              # readiness:
              #   enabled: true
              # startup:
              #   enabled: true

    service:
      app:
        controller: *app
        ports:
          http:
            port: 3001
            protocol: TCP

    persistence:
      config:
        existingClaim: uptime
        advancedMounts:
          uptime:
            app:
              - path: /app/data